

pipeline {
    agent any

    tools {
    terraform 'terraform-11'
    }

    environment {
        PRIVATE_KEY = credentials('aws-private-key')
    }

    stages {
        stage("git checkout") {
            steps {
                git branch: 'jenkins-ci', url: 'https://github.com/FaiyazJambotkar/semicolon-pipeline.git'
            }
        }

        stage("terraform apply") {
            steps { 
                dir('terraform') {
                    sh '''
                        terraform init
                        terraform apply -auto-approve -var "private_key_path=${PRIVATE_KEY}"
                    '''
                }
            }
        }

        stage('Destroy') {
            steps {
                dir('terraform') {
                input message: 'Do you want to do Terraform Destroy?', ok: 'Confirm', submitterParameter: 'PROCEED', parameters: [
                    booleanParam(defaultValue: false, description: 'Check this box to confirm Terraform Destroy', name: 'confirmDestroy')
                ]
                script {
                    if (params.confirmDestroy == true) {
                    // echo('You did not confirm the destroy operation')
                    // } 
                    // else {
                        sh 'terraform destroy --auto-approve'
                    }
                }
                }
            }
        }

    }
}